// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKf2EtRM3HqUDRQxiCUcILOx9st29bAXs',
    appId: '1:212197894639:web:85d59c453bebec4518ee1a',
    messagingSenderId: '212197894639',
    projectId: 'expenses-tracker-applica-d0e19',
    authDomain: 'expenses-tracker-applica-d0e19.firebaseapp.com',
    storageBucket: 'expenses-tracker-applica-d0e19.firebasestorage.app',
    measurementId: 'G-7XXC1HL2FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP738A9CyJ-uYSl6mEWf43BNouPwkd9E4',
    appId: '1:212197894639:android:a0009cbd49bca67e18ee1a',
    messagingSenderId: '212197894639',
    projectId: 'expenses-tracker-applica-d0e19',
    storageBucket: 'expenses-tracker-applica-d0e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbtN8gKxJY-idbsQuVr3k3lxoBdmYgmug',
    appId: '1:212197894639:ios:3f0d6751ad0007c518ee1a',
    messagingSenderId: '212197894639',
    projectId: 'expenses-tracker-applica-d0e19',
    storageBucket: 'expenses-tracker-applica-d0e19.firebasestorage.app',
    iosBundleId: 'com.example.act3SmartExpensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbtN8gKxJY-idbsQuVr3k3lxoBdmYgmug',
    appId: '1:212197894639:ios:3f0d6751ad0007c518ee1a',
    messagingSenderId: '212197894639',
    projectId: 'expenses-tracker-applica-d0e19',
    storageBucket: 'expenses-tracker-applica-d0e19.firebasestorage.app',
    iosBundleId: 'com.example.act3SmartExpensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKf2EtRM3HqUDRQxiCUcILOx9st29bAXs',
    appId: '1:212197894639:web:9b203837ec164edb18ee1a',
    messagingSenderId: '212197894639',
    projectId: 'expenses-tracker-applica-d0e19',
    authDomain: 'expenses-tracker-applica-d0e19.firebaseapp.com',
    storageBucket: 'expenses-tracker-applica-d0e19.firebasestorage.app',
    measurementId: 'G-KJWSJENR21',
  );
}
